### ISSUE TITLE
ProPresenter Media Sweep just emptied and deleted the Assets folder 

### ISSUE THREAD

**Issue by ghost** [arlinsandbulte/Pro7-Media-Sweeper#14]
As reported on the ProPresenter Users forum on Facebook, the Media Sweep did not work for me, it just emptied the entire Media Assets folder and deleted the folder, I repaired the situation by running again and using the log file. Recent log files attached, let me know what other files are needed. Thanks.
[Log.txt](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11871310/Log.txt)
[CCLIData.txt](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11871311/CCLIData.txt)
[Log.1.txt](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11871312/Log.1.txt)
[Log.2.txt](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11871315/Log.2.txt)

**Comment by arlinsandbulte** [comment]
Thanks,
The log files you attached are ProPresener7 log files.
I need to look at the Pro7 Media Sweeper log file that was generated when you had the issue.
The log filename will look something like this: Sweep_Log (20230405-074225).log
The numbers are the end are a date & time code when the sweep was performed.

**Comment by BulldogGH** [comment]
Adding the sweeper log files. Thanks.
[Sweep_Log (20230624-092726).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11874889/Sweep_Log.20230624-092726.log)
[Sweep_Log (20230624-092809).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11874890/Sweep_Log.20230624-092809.log)
[Sweep_Log (20220216-111448).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11874891/Sweep_Log.20220216-111448.log)

**Comment by arlinsandbulte** [comment]
I think the issue is somehow related to OneDrive.
In Pro7 Preferences -> Advanced:

1. Do you have "Manage Media Automatically" checked or unchecked?
2. What is your Support Files Path?

![Pro7 Prefs](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/20544649/6f2b1e05-0eb6-4094-babd-2f6552d35bf3)

**Comment by BulldogGH** [comment]
Thanks. Interesting. OneDrive can b e a mixed blessing for sure, very useful across devices but with the constant sync'ing it can get confused and sometimes I have to wait for it to calm down in order to rename a file or for Outlook to work properly.  These are my settings in ProPresenter on my build laptop, I build each week on my Windows 10 laptop, then to a full sync to/from Repository to the church Windows 11 "show" computer for the Sunday service. Thanks for reviewing for me, please let me know any changes that you recommend.

 

 



 

 

- John N.

**Comment by arlinsandbulte** [comment]
If you added a screenshot of your settings in ProPresenter, I can't see it.
Mostly, I just need to know if you have "Manage Media Automatically" checked or not.

I've never had good results using OneDrive sync with ProPresenter (or Dropbox or any other auto-sync service).  But, it has been a long time since I tried it.  Regardless, I avoid cloud sync with Pro7.  There are lots of posts about loosing all Pro7 content, and usually the issue is due to auto cloud sync.

From the log files, your media is all in 'C:\Users\Norri\OneDrive\Documents\ProPresenter\Media\Assets\'
But, your support files are in 'C:\Users\Norri\Documents\ProPresenter\'
When the utility analyzes the playlist and other files in 'C:\Users\Norri\Documents\ProPresenter\', it is not finding anything.  So, it thinks all of the media files in 'C:\Users\Norri\OneDrive\Documents\ProPresenter\Media\Assets\' are not used and they can be removed.

I suspect that your support file location should be changed to 'C:\Users\Norri\OneDrive\Documents\ProPresenter\' and it might work correctly.  But, I'd still recommend disabling OneDrive for your Documents folder.

**Comment by BulldogGH** [comment]
Thanks. My screenshot was in the body of the email, I responded from Outlook, I guess that does not work well. Screenshot now attached. I use OneDrive extensively for reasons outside of church and ProP, not sure how to disconnect one set of folders, will check that out. I do not sync across devices with OneDrive, I use to/from Repository for that, and copy the Repository folder completely from one device to the other. That was the reason for using Media Sweeper, the Repository folder had started to include all ProContent which is a real storage hog. Do you recommend unchecking "Manage Media Automatically?"
![Screenshot_ProP_file settings](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/137836297/f654c2c6-c810-414d-81d4-f420dac6c9df)

**Comment by arlinsandbulte** [comment]
I usually recommend leaving 'Manage Media Automatically' checked (enabled).

Strange... 
The Support Files path in your Pro7 settings shows 'C:\Users\Norri\OneDrive\ProPresenter\'
But, the Sweeper Utility is finding 'C:\Users\Norri\Documents\ProPresenter\' as the the Support Files path in its log.

Can you find the `PathSettings.proPaths` file and attach it here?
That file is located in `%appdata%\RenewedVision\ProPresenter\`
Or `C:\Users\Norri\AppData\Roaming\RenewedVision\ProPresenter\`

**Comment by BulldogGH** [comment]
Thanks for your patience on this. I do not have a file named PathSettings.proPaths anywhere in my AppData folders. The folder C:\Users\Norri\AppData\Roaming\RenewedVision\ProPresenter\Preferences contains these files, ZIP uploaded.
[Preferences.zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11885722/Preferences.zip)

**Comment by arlinsandbulte** [comment]
OK, I basically know what is going on now.  But, I'm not real sure why or how to fix it yet.
As a work-around, could you try placing the attached PathSettings.proPaths file into your `C:\Users\Norri\AppData\Roaming\RenewedVision\ProPresenter\` folder?
[PathSettings.proPaths.zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11886421/PathSettings.proPaths.zip)

Normally, Sweeper looks for the PathSettings.proPaths file to know what the Support Files path setting is set to in ProPresenter's settings.
If PathSettings.proPaths is not found, Sweeper uses the default setting of `%userprofile%\Documents\ProPresenter\`
If PathSettings.proPaths is found, Sweeper uses the folder path stored in that file.

That has always worked well for me.  But, apparently, if OneDrive backup is enabled for your Documents folder, ProPresenter has another way to set the correct Support Files path.  I might need to add some logic to the Sweeper app for that case.

Thank you for your help and patience with me.

**Comment by BulldogGH** [comment]
No problem, but should the .proPaths file go in the ProPresenter folder or in the ProPresenter/Preferences folder?  I am happy to make any other changes that might help you resolve this for me and for others.

**Comment by arlinsandbulte** [comment]
It should go into the ProPresenter\ folder.
Not sure why, but that is the only setting file that gets placed in that location.

**Comment by BulldogGH** [comment]
The file has been loaded. Is there some test I should run.

**Comment by arlinsandbulte** [comment]
First, just open ProPresenter.  Make sure ProPresenter loads correctly.
Then, open Pro7 Media Sweeper.  The folder to sweep should be pre-set to `C:\Users\Norri\OneDrive\Documents\ProPresenter\Media`
Then, run the Sweep and see if it works as it should.

If it works or not, post the Sweep log file here so I can look at that.

**Comment by BulldogGH** [comment]
Ran the test, report and log uploaded here, all good.  Thanks so much.
[Sweep_Log (20230627-181327).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11887823/Sweep_Log.20230627-181327.log)
[Pro7 Media Sweeper Test 2023-06-27 1830.pdf](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/11887827/Pro7.Media.Sweeper.Test.2023-06-27.1830.pdf)

**Comment by arlinsandbulte** [comment]
Great!
I think I have a plan to fix this for good.
Thanks so much for all of your help!

**Comment by BulldogGH** [comment]
Happy to help. Let me know if more needed. Thanks.

**Comment by arlinsandbulte** [comment]
The v2.3.1 release should fully resolve this issue for anyone.
@BulldogGH : You should be able to delete the PathSettings.proPaths file in `C:\Users\Norri\AppData\Roaming\RenewedVision\ProPresenter\`  That workaround should no longer be needed.
Thanks for all of your help!

**Comment by BulldogGH** [comment]
File deleted.  Thanks.

 

- John N.
