### ISSUE TITLE
Media Sweeper Flagged by Major Anti-virus Softwares.

### ISSUE THREAD

**Issue by kevint024** [arlinsandbulte/Pro7-Media-Sweeper#15]
Hello! After reading a post from someone with an issue from the Pro 7 community, it appears as if all releases of Media Sweeper are flagged as a Trojan by a significant amount of Anti-Virus softwares.  Behavioral analysis suggests that this is not the case, but I would like to seek further clarification on why the software may be setting off alarms.

Virus Total Detection Link: [https://www.virustotal.com/gui/file/993b7cd6ed15aefa7445df9c1ab191f78034526eaf7e95d0851a5e066acdac50/summary](https://www.virustotal.com/gui/file/993b7cd6ed15aefa7445df9c1ab191f78034526eaf7e95d0851a5e066acdac50/summary)

**Comment by arlinsandbulte** [comment]
I'm not an expert regarding this, but it seems like a common issue with small projects.
Media Sweeper does muck around with files in the user's Documents folder (just scans Pro7 files and moves media files).  So, maybe that triggers the malware warnings.
I've done some googling but never came up with a straight-forward method to resolve this annoyance.
If anyone knows how to certify this as not malware, feel free to let me know.

**Comment by greyshirtguy** [comment]
FWIW - Some light reading from various users over the last 6 years facing this same problem (coming up with all sorts of dances to avoid being flagged as a false positive)....
https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

The link to https://python.plainenglish.io/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184 is interesting.

That said, the fastest route might be to send it to AVG (and others) and ask for them to review for false positive.
eg AVG: https://www.avg.com/en-au/false-positive-file-form

Longer term, it looks like paying for code signing might be a route to eventually build a reputation to get the app whitelisted in most AV softwares

**Comment by greyshirtguy** [comment]
FYI: I re-compiled using pyinstaller 5.13.0 on Windows 11 [Version 10.0.22621.1992] with Python 3.10.11 installed.
<img width="359" alt="image" src="https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/1886513/933e0fd2-1538-46b4-8868-7b06e6d2107d">

And only got 1 (or 2???) detected "virus" on [virustotal](https://www.virustotal.com/gui/file/cdbde81e3267cffd69b1b761353eab02fbc29981dae1522cbf3d73df95d6a15a/detection) - Because it seems that simply using different versions of  Python/Pyinstaller can affect false positives....

<img width="453" alt="image" src="https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/1886513/658190ad-aa2d-49b5-9a2c-ef741dcf5838">

If you want, here it is: 
[Pro7 Media Sweeper.zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/12209265/Pro7.Media.Sweeper.zip)

Another thing to perhaps consider is to install the free trial of AVG and scan your system and proove it's clean (expect the false positive of Media Sweeper).....

**Comment by greyshirtguy** [comment]
FWIW Here is a recompiled .exe made on Win11 [Version 10.0.22621.1992]
pyinstaller --version 5.13.0
python --version 3.10.11

When uploaded to Virustotal.com, it scores quite a few less [(false?) positives:](https://www.virustotal.com/gui/file/7a8eb379efb5f744ade7ac3fa4f619525f06abb77c07f23774265ecb187374dc/detection)
_I guess just rebuilding with a diff environment and versions of Python/Pyinsrtaller will change the # of false positive these "wonderful guessing engines" will come up with_ ¯\\\_(ツ)\_/¯ 
<img width="814" alt="image" src="https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/1886513/c3ed10e7-326b-4b07-a376-cf849cb7ba36">


[Pro7 Media Sweeper.zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/12209358/Pro7.Media.Sweeper.zip)

**Comment by arlinsandbulte** [comment]
From https://github.com/pyinstaller/pyinstaller/issues/6754:
> The only way you can avoid getting false positives is to sign your executable, which requires paying for a certificate.
> The false positives occur because some people use PyInstaller for malware, and PyInstaller's bootloader is the only guaranteed common piece between them all.

Personally, I don't want to work through both the cost and complexity of signing my executable code with a certificate.
So, I am going to close this issue out as "Won't Fix"
