### ISSUE TITLE
Apple Issue - unable to verify

### ISSUE THREAD

**Issue by ExPastorDrew** [arlinsandbulte/Pro7-Media-Sweeper#16]
I have downloaded the Pro7.Media.Sweeper.Mac-x86_64.v2.3.2 and get the following message when I attempt to use it.  "“Pro7 Media Sweeper” can’t be opened because Apple cannot check it for malicious software."

Do you have a work around on this?

Thanks

**Comment by arlinsandbulte** [comment]
@ExPastorDrew 
Right click or Control Click and choose Open instead of double clicking it.

https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac
![FB_IMG_1700836765928](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/assets/20544649/2781a346-128b-4093-b7cc-60b188b072c8)

**Comment by arlinsandbulte** [comment]
I have added instructions on how to work around this for both Windows and Mac to the readme file.
